# Generated by Django 4.2.5 on 2023-09-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patentNotice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patentnotice",
            name="date",
            field=models.TextField(),
        ),
    ]
