# Generated by Django 4.2.5 on 2023-09-23 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("patentNotice", "0002_alter_patentnotice_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatentNoticeDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("image", models.TextField()),
                ("image_url", models.TextField()),
                ("date", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="patentnotice",
            name="date",
        ),
        migrations.AlterField(
            model_name="patentnotice",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="patentNotice.patentnoticedate",
            ),
        ),
    ]
