# Generated by Django 4.2.5 on 2023-09-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patentNotice", "0003_patentnoticedate_remove_patentnotice_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patentnoticedate",
            name="date",
        ),
        migrations.RemoveField(
            model_name="patentnoticedate",
            name="image",
        ),
        migrations.RemoveField(
            model_name="patentnoticedate",
            name="image_url",
        ),
    ]
